[CmdletBinding()]
param(
    [string]$ProjectPath = "",
    [string]$PublishedAppPath = "",
    [string]$CollectorPath = "",
    [string]$InstallRoot = "C:\temp\o365audit",
    [string]$ServiceName = "O365AuditTool",
    [ValidateRange(1, 65535)]
    [int]$Port = 5080,
    [ValidateRange(1, 65535)]
    [int]$HealthPort = 5081,
    [string]$DashboardDnsName = "",
    [string]$TlsCertificateThumbprint = "",
    [switch]$AllowInsecureHttpDashboard,
    [switch]$AutoConfigure,
    [string]$PsExecPath = "C:\Tools\PsExec\psexec.exe",
    [string]$CollectorSharePath = "",
    [string]$CollectorShareName = "o365audit",
    [string]$DomainComputersGroup = "",
    [string[]]$FallbackTargets = @(),
    [string]$DefaultOuFilter = "",
    [string]$DefaultSiteFilter = "",
    [string[]]$ExcludeDeviceNames = @(),
    [string[]]$ExcludeOus = @(),
    # Domain-joined appliances (Synology/NAS, Samba) carry an empty operatingSystem attribute and can
    # never run the collector. Off by default because a blank attribute is a hint, not proof: a real but
    # never-booted workstation looks identical. Turn it on once the appliances are identified.
    [switch]$ExcludeUnknownOperatingSystem,
    [string[]]$AuditAdminGroups = @(),
    [string[]]$AuditReaderGroups = @(),
    [string[]]$MigrationPlannerGroups = @(),
    [string]$GmsaAccount = "",
    [PSCredential]$ServiceCredential,
    [switch]$AllowLocalSystem,
    [switch]$AllowUnsignedPsExec,
    [switch]$EnableArtifactCopy,
    [switch]$DisableArtifactCopy,
    [string]$CopyTargetRoot = "",
    [string[]]$AllowedCopyTargetRoots = @(),
    [string[]]$AllowedCopySourceUncRoots = @(),
    [switch]$CopyVerifySha256,
    [switch]$DisableCopySha256,
    [switch]$SkipPublish,
    [switch]$FunctionsOnly
)

$ErrorActionPreference = 'Stop'

# Operator intent has to be captured BEFORE the redeploy preservation block repopulates
# $TlsCertificateThumbprint from the existing appsettings.Production.json. Deriving intent later from
# "the variable is non-empty" would treat every routine redeploy as an explicit operator selection and
# silently promote whatever certificate is configured into the machine-wide trusted root store.
$script:TlsThumbprintExplicitlySupplied = $PSBoundParameters.ContainsKey('TlsCertificateThumbprint')
$script:ExcludeUnknownOperatingSystemExplicitlySupplied = $PSBoundParameters.ContainsKey('ExcludeUnknownOperatingSystem')
if ($CopyVerifySha256 -and $DisableCopySha256) {
    throw 'CopyVerifySha256 ve DisableCopySha256 birlikte kullanilamaz.'
}
if ($EnableArtifactCopy -and $DisableArtifactCopy) {
    throw 'EnableArtifactCopy ve DisableArtifactCopy birlikte kullanilamaz.'
}

$existingServiceAccountToPreserve = ''

# A certificate carrying this friendly name was generated by this script, so re-selecting it on a
# redeploy is still the script's own certificate and may be trusted locally.
$automaticTlsCertificateFriendlyName = 'O365AuditTool automatic TLS'

# UseWindowsService() logs under the application name, not under -ServiceName.
$eventLogSourceName = 'O365AuditTool'

function Assert-Admin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Bu script Administrator yetkisi ile calistirilmalidir."
    }
}

function Ensure-Directory([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Get-ObjectPathValue {
    param(
        [object]$InputObject,
        [string[]]$Path,
        [object]$DefaultValue = $null
    )

    $current = $InputObject
    foreach ($segment in $Path) {
        if ($null -eq $current) { return $DefaultValue }
        $property = $current.PSObject.Properties[$segment]
        if ($null -eq $property) { return $DefaultValue }
        $current = $property.Value
    }
    if ($null -eq $current) { return $DefaultValue }
    return $current
}

function Assert-NoReparsePointInPath {
    param([Parameter(Mandatory)][string]$Path)

    $fullPath = [IO.Path]::GetFullPath($Path)
    $root = [IO.Path]::GetPathRoot($fullPath)
    $current = $root
    foreach ($segment in $fullPath.Substring($root.Length).Split([char[]]'\/', [StringSplitOptions]::RemoveEmptyEntries)) {
        $current = Join-Path $current $segment
        if (-not (Test-Path -LiteralPath $current)) {
            continue
        }

        $item = Get-Item -LiteralPath $current -Force
        if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw "Yonetilen deployment path'i reparse point iceremez: '$current'."
        }
    }
}

function Assert-NoReparsePointTree {
    param([Parameter(Mandatory)][string]$Root)

    Assert-NoReparsePointInPath -Path $Root
    $reparseItem = Get-ChildItem -LiteralPath $Root -Force -Recurse -ErrorAction Stop |
        Where-Object { ($_.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0 } |
        Select-Object -First 1
    if ($null -ne $reparseItem) {
        throw "Deployment kaynak agaci reparse point iceremez: '$($reparseItem.FullName)'."
    }
}

function Assert-DirectoryCopyIntegrity {
    param(
        [Parameter(Mandatory)][string]$SourceRoot,
        [Parameter(Mandatory)][string]$DestinationRoot
    )

    $normalizedSource = [IO.Path]::GetFullPath($SourceRoot).TrimEnd('\') + '\'
    foreach ($sourceFile in (Get-ChildItem -LiteralPath $SourceRoot -File -Force -Recurse)) {
        $relativePath = $sourceFile.FullName.Substring($normalizedSource.Length)
        $destinationFile = Join-Path $DestinationRoot $relativePath
        if (-not (Test-Path -LiteralPath $destinationFile -PathType Leaf)) {
            throw "Deployment copy dogrulamasi hedef dosyayi bulamadi: '$destinationFile'."
        }

        $sourceHash = (Get-FileHash -LiteralPath $sourceFile.FullName -Algorithm SHA256).Hash
        $destinationHash = (Get-FileHash -LiteralPath $destinationFile -Algorithm SHA256).Hash
        if (-not $sourceHash.Equals($destinationHash, [StringComparison]::OrdinalIgnoreCase)) {
            throw "Deployment copy SHA256 dogrulamasi basarisiz: '$relativePath'."
        }
    }
}

function Resolve-DashboardDnsName {
    param([string]$ExplicitName)

    $name = $ExplicitName.Trim().TrimEnd('.')
    if ([string]::IsNullOrWhiteSpace($name)) {
        try {
            $computerSystem = Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction Stop
            if ($computerSystem.PartOfDomain -and -not [string]::IsNullOrWhiteSpace([string]$computerSystem.Domain)) {
                $name = "$env:COMPUTERNAME.$($computerSystem.Domain)"
            }
        }
        catch {}

        if ([string]::IsNullOrWhiteSpace($name)) {
            $name = $env:COMPUTERNAME
        }
    }

    if ($name.Length -gt 253 -or $name -notmatch '^(?=.{1,253}$)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(?:\.(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?))*$') {
        throw "DashboardDnsName gecerli bir DNS hostname veya FQDN degil: '$name'."
    }

    return $name.ToLowerInvariant()
}

function Merge-WindowsAuthServerAllowlist {
    param(
        [string]$ExistingValue,
        [Parameter(Mandatory)][string]$ServerName
    )

    $values = @(
        @($ExistingValue -split ',')
        $ServerName
    ) |
        ForEach-Object { $_.Trim() } |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        Select-Object -Unique |
        Sort-Object
    return ($values -join ',')
}

function Set-LocalBrowserSsoPolicy {
    param([Parameter(Mandatory)][string]$ServerName)

    $edgePolicyPath = 'HKLM:\SOFTWARE\Policies\Microsoft\Edge'
    New-Item -Path $edgePolicyPath -Force | Out-Null
    $existingAllowlist = [string](Get-ItemProperty `
        -Path $edgePolicyPath `
        -Name 'AuthServerAllowlist' `
        -ErrorAction SilentlyContinue).AuthServerAllowlist
    $authServerAllowlist = Merge-WindowsAuthServerAllowlist `
        -ExistingValue $existingAllowlist `
        -ServerName $ServerName
    New-ItemProperty `
        -Path $edgePolicyPath `
        -Name 'AuthServerAllowlist' `
        -PropertyType String `
        -Value $authServerAllowlist `
        -Force | Out-Null

    $zoneMapPath = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMapKey'
    New-Item -Path $zoneMapPath -Force | Out-Null
    New-ItemProperty `
        -Path $zoneMapPath `
        -Name "https://$ServerName" `
        -PropertyType String `
        -Value '1' `
        -Force | Out-Null

    Write-Host "Yerel Edge/Windows Integrated Authentication policy ayarlandi: $ServerName" -ForegroundColor DarkCyan
    Write-Warning 'Bu ayar yalnizca yonetim sunucusuna uygulanir. Diger domain istemcilerine ayni AuthServerAllowlist ve Local Intranet zone degerlerini GPO ile dagitin; credential delegation allowlist etkinlestirmeyin.'
}

function Test-CertificateDnsName {
    param(
        [Parameter(Mandatory)][string]$CertificateName,
        [Parameter(Mandatory)][string]$RequestedName
    )

    $certificateName = $CertificateName.Trim().TrimEnd('.').ToLowerInvariant()
    $requestedName = $RequestedName.Trim().TrimEnd('.').ToLowerInvariant()
    if ($certificateName.Equals($requestedName, [StringComparison]::OrdinalIgnoreCase)) {
        return $true
    }
    if (-not $certificateName.StartsWith('*.')) {
        return $false
    }

    $suffix = $certificateName.Substring(1)
    if (-not $requestedName.EndsWith($suffix, [StringComparison]::OrdinalIgnoreCase)) {
        return $false
    }

    $prefix = $requestedName.Substring(0, $requestedName.Length - $suffix.Length)
    return $prefix.Length -gt 0 -and -not $prefix.Contains('.')
}

function Get-CertificateDnsNames {
    param([Parameter(Mandatory)]$Certificate)

    $names = @()
    if ($null -ne $Certificate.DnsNameList) {
        $names = @($Certificate.DnsNameList | ForEach-Object { [string]$_.Unicode })
    }
    if ($names.Count -eq 0) {
        $fallbackName = $Certificate.GetNameInfo(
            [Security.Cryptography.X509Certificates.X509NameType]::DnsName,
            $false)
        if (-not [string]::IsNullOrWhiteSpace($fallbackName)) {
            $names = @($fallbackName)
        }
    }

    return @($names | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique)
}

function Test-TlsCertificateCandidate {
    param(
        [Parameter(Mandatory)]$Certificate,
        [Parameter(Mandatory)][string]$DnsName
    )

    if (-not $Certificate.HasPrivateKey) {
        return $false
    }
    if ($Certificate.NotAfter.ToUniversalTime() -le [DateTime]::UtcNow) {
        return $false
    }
    if ($Certificate.NotBefore.ToUniversalTime() -gt [DateTime]::UtcNow) {
        return $false
    }

    $ekuExtension = $Certificate.Extensions |
        Where-Object { $_.Oid.Value -eq '2.5.29.37' } |
        Select-Object -First 1
    if ($null -eq $ekuExtension -or -not ($ekuExtension.EnhancedKeyUsages | Where-Object { $_.Value -eq '1.3.6.1.5.5.7.3.1' })) {
        return $false
    }

    return [bool](Get-CertificateDnsNames -Certificate $Certificate |
        Where-Object { Test-CertificateDnsName -CertificateName $_ -RequestedName $DnsName } |
        Select-Object -First 1)
}

function New-AutomaticTlsCertificate {
    param([Parameter(Mandatory)][string]$DnsName)

    $dnsNames = @($DnsName, $env:COMPUTERNAME) |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        Select-Object -Unique
    $getCertificate = Get-Command Get-Certificate -ErrorAction SilentlyContinue
    if ($getCertificate) {
        try {
            Write-Host "AD CS Machine sertifika enrollment deneniyor: $DnsName" -ForegroundColor DarkCyan
            $enrollment = Get-Certificate `
                -Template 'Machine' `
                -DnsName $dnsNames `
                -CertStoreLocation 'Cert:\LocalMachine\My' `
                -ErrorAction Stop
            if (
                $null -ne $enrollment.Certificate -and
                (Test-TlsCertificateCandidate -Certificate $enrollment.Certificate -DnsName $DnsName)
            ) {
                return $enrollment.Certificate
            }

            Write-Warning 'AD CS enrollment bir sertifika dondurdu ancak sertifika TLS gereksinimlerini karsilamadi.'
        }
        catch {
            Write-Warning "AD CS Machine enrollment kullanilamadi: $($_.Exception.Message)"
        }
    }

    $newSelfSignedCertificate = Get-Command New-SelfSignedCertificate -ErrorAction SilentlyContinue
    if (-not $newSelfSignedCertificate) {
        throw 'Otomatik TLS icin uygun sertifika bulunamadi ve New-SelfSignedCertificate kullanilamiyor.'
    }

    Write-Warning 'Kurumsal CA sertifikasi bulunamadi. HTTPS icin self-signed sertifika uretiliyor; istemci guveni GPO veya kurumsal PKI ile ayrica dagitilmalidir.'
    return New-SelfSignedCertificate `
        -Type SSLServerAuthentication `
        -Subject "CN=$DnsName" `
        -DnsName $dnsNames `
        -CertStoreLocation 'Cert:\LocalMachine\My' `
        -FriendlyName $automaticTlsCertificateFriendlyName `
        -KeyAlgorithm RSA `
        -KeyLength 2048 `
        -HashAlgorithm SHA256 `
        -KeyExportPolicy NonExportable `
        -NotAfter (Get-Date).AddYears(2)
}

function Test-SelfSignedCertificate {
    param([Parameter(Mandatory)]$Certificate)

    return $Certificate.Subject.Equals($Certificate.Issuer, [StringComparison]::OrdinalIgnoreCase)
}

function Test-CertificateChainTrust {
    param([Parameter(Mandatory)]$Certificate)

    # Program.cs resolves the TLS certificate with X509Store.Find(..., validOnly: $true). The Windows store
    # search suppresses revocation checking, so revocation is disabled here too: on an MSP domain controller
    # with no outbound internet an AD CS certificate whose CRL endpoint is unreachable would otherwise be
    # reported as untrusted even though the service loads it happily.
    $chain = New-Object Security.Cryptography.X509Certificates.X509Chain
    $chain.ChainPolicy.RevocationMode = [Security.Cryptography.X509Certificates.X509RevocationMode]::NoCheck
    try {
        $built = $chain.Build($Certificate)
        $statusFlags = @($chain.ChainStatus | ForEach-Object { [string]$_.Status } | Select-Object -Unique)
        return @{
            Trusted = [bool]$built
            Status = $statusFlags
        }
    }
    finally {
        if ($chain -is [IDisposable]) {
            $chain.Dispose()
        }
    }
}

function Import-TrustedRootCertificate {
    param([Parameter(Mandatory)]$Certificate)

    # RawData is the DER encoding of the certificate alone, so the private key stays in LocalMachine\My.
    $publicCertificate = New-Object `
        -TypeName Security.Cryptography.X509Certificates.X509Certificate2 `
        -ArgumentList (, $Certificate.RawData)
    $rootStore = New-Object `
        -TypeName Security.Cryptography.X509Certificates.X509Store `
        -ArgumentList @('Root', [Security.Cryptography.X509Certificates.StoreLocation]::LocalMachine)
    try {
        $rootStore.Open([Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
        $rootStore.Add($publicCertificate)
    }
    finally {
        $rootStore.Close()
        if ($publicCertificate -is [IDisposable]) {
            $publicCertificate.Dispose()
        }
    }
}

function Ensure-SelfSignedCertificateTrust {
    param(
        [Parameter(Mandatory)]$Certificate,
        [Parameter(Mandatory)][bool]$TrustAllowed
    )

    $thumbprint = [string]$Certificate.Thumbprint
    $chainResult = Test-CertificateChainTrust -Certificate $Certificate
    if ($chainResult.Trusted) {
        return
    }

    if (-not (Test-SelfSignedCertificate -Certificate $Certificate)) {
        Write-Warning ("TLS sertifika zinciri dogrulanamadi: $thumbprint (durum: $($chainResult.Status -join ', ')). " +
                       "Sertifika bir CA tarafindan verilmis; kok ve ara CA sertifikalarini LocalMachine\Root ve " +
                       "LocalMachine\CA depolarina siz dagitmalisiniz. Baskasina ait sertifika otomatik guvenilir yapilmaz.")
        return
    }

    $basicConstraints = $Certificate.Extensions | Where-Object { $_.Oid.Value -eq '2.5.29.19' } | Select-Object -First 1
    if ($basicConstraints -and $basicConstraints.CertificateAuthority) {
        # A leaf certificate in Root can only vouch for itself. A CA=true certificate in Root becomes a
        # machine-wide issuing authority for ANY hostname on a domain controller, which is an unbounded
        # trust delegation and never something a deployment should grant on its own.
        throw ("TLS sertifikasi CA (basicConstraints CA=true) olarak isaretli: $thumbprint. Bu sertifika " +
               "LocalMachine\Root deposuna otomatik eklenmez; makine genelinde sinirsiz guven delegasyonu olur. " +
               "Yalnizca sunucu (leaf) sertifikasi kullanin veya guveni bilincli olarak siz dagitin.")
    }

    if (-not $TrustAllowed) {
        Write-Warning ("Self-signed TLS sertifikasi LocalMachine\Root deposunda degil: $thumbprint " +
                       "(durum: $($chainResult.Status -join ', ')). Sertifika bu script tarafindan uretilmedigi ve " +
                       "-TlsCertificateThumbprint ile acikca secilmedigi icin otomatik guvenilir yapilmadi. " +
                       "Bilincli olarak kullanacaksaniz '-TlsCertificateThumbprint $thumbprint' ile calistirin.")
        return
    }

    # BURCUDC: the self-signed certificate had been imported into LocalMachine\CA (intermediate) and never
    # into Root, so the chain stayed UntrustedRoot, the validOnly lookup in Program.cs found nothing and the
    # service threw on startup. Only the public part is imported and only for certificates this script owns.
    try {
        Import-TrustedRootCertificate -Certificate $Certificate
        Write-Host "Self-signed TLS sertifikasinin public bolumu LocalMachine\Root deposuna eklendi: $thumbprint" -ForegroundColor DarkCyan
    }
    catch {
        Write-Warning "Self-signed TLS sertifikasi LocalMachine\Root deposuna eklenemedi: $thumbprint. $($_.Exception.Message)"
    }

    $verifiedChain = Test-CertificateChainTrust -Certificate $Certificate
    if ($verifiedChain.Trusted) {
        Write-Host "TLS sertifika zinciri dogrulandi: $thumbprint" -ForegroundColor DarkCyan
        return
    }

    Write-Warning ("TLS sertifika zinciri Root importundan sonra da dogrulanamadi: $thumbprint " +
                   "(durum: $($verifiedChain.Status -join ', ')). Servis sertifikayi yalnizca gecerli zincir ile " +
                   "arar, bu haliyle baslatilamaz. 'Get-ChildItem Cert:\LocalMachine\Root\$thumbprint' ile " +
                   "sertifikanin Root deposunda oldugunu dogrulayin; sertifika yalnizca LocalMachine\CA icinde " +
                   "duruyorsa zincir UntrustedRoot kalir.")
}

function Remove-DeploymentDirectory {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Root
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        return
    }

    $resolvedRoot = [IO.Path]::GetFullPath($Root).TrimEnd('\') + '\'
    $resolvedPath = [IO.Path]::GetFullPath($Path)
    $leaf = Split-Path $resolvedPath -Leaf
    if (
        -not $resolvedPath.StartsWith($resolvedRoot, [StringComparison]::OrdinalIgnoreCase) -or
        $leaf -notmatch '^\.(?:staging|rollback|failed)-[0-9a-f]{32}$'
    ) {
        throw "Guvenli olmayan deployment cleanup path'i reddedildi: '$resolvedPath'."
    }

    Remove-Item -LiteralPath $resolvedPath -Recurse -Force
}

function Resolve-TlsCertificateThumbprint {
    param(
        [string]$Thumbprint,
        [bool]$AllowInsecure,
        [string]$DnsName,
        [bool]$AutoConfigure
    )

    if ($AllowInsecure) {
        Write-Warning 'Dashboard HTTP istisnasi etkin. Bu mod yalnizca izole test aginda kullanilmalidir.'
        return ''
    }
    $operatorSelectedCertificate = $script:TlsThumbprintExplicitlySupplied
    $scriptManagedCertificate = $false
    if ([string]::IsNullOrWhiteSpace($Thumbprint) -and $AutoConfigure) {
        $certificate = Get-ChildItem -Path 'Cert:\LocalMachine\My' -ErrorAction SilentlyContinue |
            Where-Object { Test-TlsCertificateCandidate -Certificate $_ -DnsName $DnsName } |
            Sort-Object NotAfter -Descending |
            Select-Object -First 1
        if ($null -eq $certificate) {
            $certificate = New-AutomaticTlsCertificate -DnsName $DnsName
            $scriptManagedCertificate = $true
        }
        elseif ([string]$certificate.FriendlyName -eq $automaticTlsCertificateFriendlyName) {
            $scriptManagedCertificate = $true
        }
        if ($null -eq $certificate -or [string]::IsNullOrWhiteSpace([string]$certificate.Thumbprint)) {
            throw "DashboardDnsName '$DnsName' icin otomatik TLS sertifikasi olusturulamadi."
        }

        $Thumbprint = [string]$certificate.Thumbprint
        Write-Host "TLS sertifikasi otomatik secildi: $Thumbprint" -ForegroundColor DarkCyan
    }
    elseif ([string]::IsNullOrWhiteSpace($Thumbprint)) {
        throw 'Production dashboard icin -TlsCertificateThumbprint zorunludur. Otomatik secim icin -AutoConfigure, yalnizca izole test icin -AllowInsecureHttpDashboard kullanilabilir.'
    }

    $normalized = ($Thumbprint -replace '\s', '').ToUpperInvariant()
    if ($normalized -notmatch '^[0-9A-F]{40,128}$') {
        throw 'TlsCertificateThumbprint gecerli hexadecimal sertifika thumbprint degerinde degil.'
    }

    $certificate = Get-Item -LiteralPath "Cert:\LocalMachine\My\$normalized" -ErrorAction SilentlyContinue
    if ($null -eq $certificate -or -not $certificate.HasPrivateKey) {
        throw "LocalMachine\\My deposunda private key iceren TLS sertifikasi bulunamadi: '$normalized'."
    }
    if ($certificate.NotAfter.ToUniversalTime() -le [DateTime]::UtcNow) {
        throw "TLS sertifikasinin suresi dolmus: '$normalized'."
    }
    if ($certificate.NotBefore.ToUniversalTime() -gt [DateTime]::UtcNow) {
        throw "TLS sertifikasi henuz gecerli degil: '$normalized'."
    }

    if (-not (Test-TlsCertificateCandidate -Certificate $certificate -DnsName $DnsName)) {
        $certificateDnsNames = @(Get-CertificateDnsNames -Certificate $certificate)
        throw "TLS sertifikasi private key, tarih, Server Authentication EKU veya DashboardDnsName '$DnsName' gereksinimini karsilamiyor. Sertifika adlari: $($certificateDnsNames -join ', ')."
    }

    Ensure-SelfSignedCertificateTrust `
        -Certificate $certificate `
        -TrustAllowed ($scriptManagedCertificate -or $operatorSelectedCertificate)

    return $normalized
}

function Ensure-HttpSpns {
    param(
        [Parameter(Mandatory)][string]$AccountName,
        [Parameter(Mandatory)][string]$DnsName
    )

    $setSpnPath = Join-Path $env:SystemRoot 'System32\setspn.exe'
    if (-not (Test-Path -LiteralPath $setSpnPath -PathType Leaf)) {
        throw "setspn.exe bulunamadi; Kerberos HTTP SPN dogrulanamiyor."
    }

    $names = @($DnsName, $DnsName.Split('.')[0]) |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        Select-Object -Unique
    foreach ($name in $names) {
        $spn = "HTTP/$name"
        $existingForAccount = @(& $setSpnPath -L $AccountName 2>&1)
        if ($LASTEXITCODE -eq 0 -and ($existingForAccount | Where-Object { $_.Trim().Equals($spn, [StringComparison]::OrdinalIgnoreCase) })) {
            continue
        }

        $result = @(& $setSpnPath -S $spn $AccountName 2>&1)
        if ($LASTEXITCODE -ne 0) {
            # Changing the service identity leaves the HTTP SPN on the previous account, so
            # setspn -S refuses as a duplicate. Migrate it only when this machine's own
            # computer account holds it -- that is the registration our own LocalSystem
            # deployment created. Any other holder is someone else's and is never touched.
            $ownComputerAccount = "$env:COMPUTERNAME`$"
            $holderLines = @(& $setSpnPath -Q $spn 2>&1)
            $holder = $holderLines |
                Where-Object { $_ -match '^\s*CN=' } |
                Select-Object -First 1
            $heldByThisComputer = $holderLines |
                Where-Object { $_ -match ("^\s*CN=" + [regex]::Escape($env:COMPUTERNAME) + ",") }

            if ($heldByThisComputer -and -not $AccountName.TrimEnd('$').Equals($env:COMPUTERNAME, [StringComparison]::OrdinalIgnoreCase)) {
                Write-Warning "SPN '$spn' bu sunucunun bilgisayar hesabinda kayitli; servis kimligi degistigi icin '$ownComputerAccount' uzerinden kaldirilip '$AccountName' hesabina tasiniyor."
                $removal = @(& $setSpnPath -D $spn $ownComputerAccount 2>&1)
                if ($LASTEXITCODE -ne 0) {
                    throw "SPN '$spn' eski hesaptan kaldirilamadi: setspn -D $spn $ownComputerAccount. Cikti: $($removal -join ' ')."
                }

                $result = @(& $setSpnPath -S $spn $AccountName 2>&1)
                if ($LASTEXITCODE -ne 0) {
                    throw "Kerberos SPN kaydedilemedi: setspn -S $spn $AccountName. Cikti: $($result -join ' ')."
                }
                continue
            }

            throw ("Kerberos SPN kaydedilemedi: setspn -S $spn $AccountName. SPN su anda '" +
                   ($(if ($holder) { $holder.Trim() } else { 'bilinmeyen bir hesap' })) +
                   "' uzerinde kayitli. Baska bir hesaba ait SPN otomatik tasinmaz; dogruysa once " +
                   "'setspn -D $spn <mevcut-hesap>' ile kaldirin. Cikti: $($result -join ' ')")
        }
    }
}

function Grant-TlsPrivateKeyRead {
    param(
        [Parameter(Mandatory)][string]$Thumbprint,
        [Parameter(Mandatory)][Security.Principal.SecurityIdentifier]$AccountSid
    )

    $certificate = Get-Item -LiteralPath "Cert:\LocalMachine\My\$Thumbprint" -ErrorAction Stop
    $key = $null
    $keyPath = $null
    try {
        $key = [Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate)
        if ($null -eq $key) {
            $key = [Security.Cryptography.X509Certificates.ECDsaCertificateExtensions]::GetECDsaPrivateKey($certificate)
        }

        if ($key -is [Security.Cryptography.RSACng] -or $key -is [Security.Cryptography.ECDsaCng]) {
            $keyPath = Join-Path $env:ProgramData "Microsoft\Crypto\Keys\$($key.Key.UniqueName)"
        }
        elseif ($key -is [Security.Cryptography.RSACryptoServiceProvider]) {
            $containerName = $key.CspKeyContainerInfo.UniqueKeyContainerName
            $keyPath = Join-Path $env:ProgramData "Microsoft\Crypto\RSA\MachineKeys\$containerName"
        }

        if ([string]::IsNullOrWhiteSpace($keyPath) -or -not (Test-Path -LiteralPath $keyPath -PathType Leaf)) {
            throw "TLS private key dosyasi cozumlenemedi. Sertifikanin machine-key olarak import edildigini dogrulayin: '$Thumbprint'."
        }

        $keyAcl = Get-Acl -LiteralPath $keyPath
        $rule = New-Object Security.AccessControl.FileSystemAccessRule(
            $AccountSid,
            [Security.AccessControl.FileSystemRights]::Read,
            [Security.AccessControl.AccessControlType]::Allow)
        $keyAcl.SetAccessRule($rule)
        Set-Acl -LiteralPath $keyPath -AclObject $keyAcl
    }
    finally {
        if ($key -is [IDisposable]) {
            $key.Dispose()
        }
    }
}

function Ensure-TlsPrivateKeyAccess {
    param(
        [Parameter(Mandatory)][string]$Thumbprint,
        [Parameter(Mandatory)][hashtable]$Identity
    )

    if ($Identity.Type -eq 'LocalSystem') {
        if ($null -eq $Identity.AclSid -or $Identity.AclSid.Value -ne 'S-1-5-18') {
            throw 'LocalSystem servis kimligi beklenen S-1-5-18 SID degerine sahip degil.'
        }

        # Machine certificate keys grant SYSTEM access by default; provider-specific file ACL lookup is unnecessary.
        Write-Verbose "LocalSystem TLS private key erisimi machine-key varsayilan ACL'i ile saglanacak."
        return
    }

    Grant-TlsPrivateKeyRead -Thumbprint $Thumbprint -AccountSid $Identity.AclSid
}

function Resolve-DotNetPath {
    param([bool]$Publishing)

    $candidates = @()
    $command = Get-Command dotnet -ErrorAction SilentlyContinue
    if ($command -and (Test-Path -LiteralPath $command.Source -PathType Leaf)) {
        $candidates += $command.Source
    }

    $candidates += @(
        $(if (-not [string]::IsNullOrWhiteSpace($env:USERPROFILE)) { Join-Path $env:USERPROFILE '.dotnet\dotnet.exe' }),
        (Join-Path $env:ProgramFiles 'dotnet\dotnet.exe'),
        'C:\Program Files\dotnet\dotnet.exe'
    ) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique

    foreach ($candidate in ($candidates | Select-Object -Unique)) {
        if (-not (Test-Path -LiteralPath $candidate -PathType Leaf)) {
            continue
        }

        if ($Publishing) {
            $sdks = @(& $candidate --list-sdks 2>$null)
            if ($LASTEXITCODE -eq 0 -and ($sdks -match '^10\.\d+\.\d+')) {
                return $candidate
            }
        }
        else {
            $runtimes = @(& $candidate --list-runtimes 2>$null)
            if ($LASTEXITCODE -eq 0 -and ($runtimes -match '^Microsoft\.ASPNetCore\.App 10\.')) {
                return $candidate
            }
        }
    }

    $requirement = if ($Publishing) { '.NET 10 SDK' } else { 'ASP.NET Core Runtime 10' }
    throw "$requirement bulunamadi. PATH, %USERPROFILE%\.dotnet ve Program Files konumlari kontrol edildi."
}

function Assert-DotNet10 {
    param(
        [string]$DotNetPath,
        [bool]$Publishing
    )

    & $DotNetPath --info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet calistirilamadi: '$DotNetPath'."
    }

    if ($Publishing) {
        $sdks = @(& $DotNetPath --list-sdks 2>$null)
        if (-not ($sdks -match '^10\.\d+\.\d+')) {
            throw ".NET 10 SDK bulunamadi. Kaynak koddan publish icin Microsoft.DotNet.SDK.10 kurulmalidir."
        }
    }

    $runtimes = @(& $DotNetPath --list-runtimes 2>$null)
    if (-not ($runtimes -match '^Microsoft\.ASPNetCore\.App 10\.')) {
        throw "ASP.NET Core Runtime 10 bulunamadi. Framework-dependent servisi calistirmak icin gereklidir."
    }
}

function Assert-PsExec {
    param(
        [string]$Path,
        [bool]$AllowUnsigned
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "PsExec bulunamadi: '$Path'. Sysinternals PsExec'i bu konuma kopyalayin veya -PsExecPath belirtin."
    }

    if ([IO.Path]::GetExtension($Path) -ne '.exe') {
        throw "PsExecPath bir .exe dosyasi gostermelidir: '$Path'."
    }

    $signature = Get-AuthenticodeSignature -LiteralPath $Path
    if ($signature.Status -ne [System.Management.Automation.SignatureStatus]::Valid -and -not $AllowUnsigned) {
        throw "PsExec imzasi gecerli degil (durum: $($signature.Status)). Dogru Sysinternals binary'sini kullanin. Bilincli istisna icin -AllowUnsignedPsExec gerekir."
    }
    if (-not $AllowUnsigned -and $signature.SignerCertificate.Subject -notmatch '(^|,\s*)CN=Microsoft Corporation(,|$)') {
        throw "PsExec Microsoft Corporation tarafindan imzalanmamis. Resmi Sysinternals binary'sini kullanin."
    }
}

function Resolve-AccountNameBySid([string]$SidValue) {
    try {
        $sid = New-Object Security.Principal.SecurityIdentifier($SidValue)
        return $sid.Translate([Security.Principal.NTAccount]).Value
    }
    catch {
        throw "SID hesap adina cevrilemedi: '$SidValue'. $($_.Exception.Message)"
    }
}

function Resolve-AccountSid([string]$AccountName) {
    try {
        $account = New-Object Security.Principal.NTAccount($AccountName)
        return $account.Translate([Security.Principal.SecurityIdentifier])
    }
    catch {
        throw "Hesap SID'e cevrilemedi: '$AccountName'. Hesabin domain'de mevcut oldugunu ve sunucunun domain erisimi oldugunu dogrulayin."
    }
}

function Resolve-DomainGroupList {
    param(
        [string]$RoleName,
        [string[]]$GroupNames
    )

    $requestedGroups = @($GroupNames | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | ForEach-Object { $_.Trim() } | Select-Object -Unique)
    if ($requestedGroups.Count -eq 0) {
        throw "$RoleName icin en az bir AD grubu belirtilmelidir. Ornek: -${RoleName}Groups 'DOMAIN\GG_O365_$RoleName'."
    }

    $resolvedGroups = @()
    $getAdGroup = Get-Command Get-ADGroup -ErrorAction SilentlyContinue
    foreach ($groupName in $requestedGroups) {
        if ($groupName -notmatch '^[^\\]+\\[^\\]+$' -or $groupName.StartsWith('.\')) {
            throw "$RoleName grup adi 'DOMAIN\GrupAdi' biciminde olmalidir: '$groupName'."
        }

        $sid = Resolve-AccountSid -AccountName $groupName
        if ($getAdGroup) {
            try {
                Get-ADGroup -Identity $sid.Value -ErrorAction Stop | Out-Null
            }
            catch {
                throw "$RoleName eslemesi bir AD grubu olarak dogrulanamadi: '$groupName'. $($_.Exception.Message)"
            }
        }

        $resolvedGroups += $sid.Translate([Security.Principal.NTAccount]).Value
    }

    if (-not $getAdGroup) {
        Write-Warning "$RoleName hesaplari SID ile cozuldu ancak ActiveDirectory modulu olmadigi icin grup nesnesi olduklari dogrulanamadi."
    }

    return @($resolvedGroups | Select-Object -Unique)
}

function Resolve-FallbackTargets([string[]]$Targets) {
    $resolvedTargets = @($Targets | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | ForEach-Object { $_.Trim() } | Select-Object -Unique)
    foreach ($target in $resolvedTargets) {
        if ($target -notmatch '^[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?$') {
            throw "Fallback target gecerli bir hostname veya FQDN degil: '$target'."
        }
    }
    return $resolvedTargets
}

function Resolve-ExcludeDeviceNames([string[]]$Names) {
    $resolvedNames = @($Names | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | ForEach-Object { $_.Trim() } | Select-Object -Unique)
    foreach ($name in $resolvedNames) {
        if ($name -notmatch '^[A-Za-z0-9_.*?-]{1,255}$') {
            throw "ExcludeDeviceNames yalnizca cihaz adi veya '*' / '?' joker karakteri iceren desen kabul eder: '$name'."
        }
    }
    return $resolvedNames
}

function Resolve-ExcludeOus([string[]]$OrganizationalUnits) {
    $resolvedOus = @($OrganizationalUnits | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | ForEach-Object { $_.Trim() } | Select-Object -Unique)
    foreach ($organizationalUnit in $resolvedOus) {
        if ($organizationalUnit -notmatch '^[A-Za-z]{1,10}=[^,]+(?:,[A-Za-z]{1,10}=[^,]+)+$') {
            throw "ExcludeOus tam distinguished name olmalidir. Ornek: 'OU=SERVER,DC=nbr,DC=local'. Gecersiz deger: '$organizationalUnit'."
        }
    }
    return $resolvedOus
}

function Resolve-CopyRoot {
    param(
        [string]$Path,
        [string]$ParameterName,
        [switch]$AllowEmpty
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        if ($AllowEmpty) {
            return ''
        }
        throw "$ParameterName bos olamaz."
    }

    $trimmedPath = $Path.Trim()
    if ($trimmedPath -notmatch '^(?:[A-Za-z]:\\|\\\\[^\\]+\\[^\\]+(?:\\|$))') {
        throw "$ParameterName tam bir yerel veya UNC path olmalidir: '$trimmedPath'."
    }

    try {
        $resolvedPath = [IO.Path]::GetFullPath($trimmedPath).TrimEnd('\')
    }
    catch {
        throw "$ParameterName normalize edilemedi: '$trimmedPath'. $($_.Exception.Message)"
    }

    if ([string]::IsNullOrWhiteSpace($resolvedPath)) {
        throw "$ParameterName gecersiz: '$trimmedPath'."
    }

    $localDriveRoot = [IO.Path]::GetPathRoot($resolvedPath).TrimEnd('\')
    if ($resolvedPath -match '^[A-Za-z]:$' -and $resolvedPath.Equals($localDriveRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "$ParameterName bir surucu kok dizini olamaz: '$resolvedPath'. Ayrilmis bir alt dizin kullanin."
    }

    return $resolvedPath
}

function Test-PathWithinRoot {
    param(
        [string]$Path,
        [string]$Root
    )

    if ($Path.Equals($Root, [StringComparison]::OrdinalIgnoreCase)) {
        return $true
    }

    return $Path.StartsWith("$Root\", [StringComparison]::OrdinalIgnoreCase)
}

function Remove-PublishedSampleMappings([string]$ApplicationDirectory) {
    $baseSettingsPath = Join-Path $ApplicationDirectory 'appsettings.json'
    if (-not (Test-Path -LiteralPath $baseSettingsPath -PathType Leaf)) {
        throw "Publish cikisinda appsettings.json bulunamadi: '$baseSettingsPath'."
    }

    $baseSettings = Get-Content -LiteralPath $baseSettingsPath -Raw | ConvertFrom-Json
    if ($null -ne $baseSettings.Collector) {
        $baseSettings.Collector.FallbackTargets = @()
    }
    if ($null -ne $baseSettings.Auth -and $null -ne $baseSettings.Auth.RoleMappings) {
        $baseSettings.Auth.RoleMappings.AuditAdmin = @()
        $baseSettings.Auth.RoleMappings.AuditReader = @()
        $baseSettings.Auth.RoleMappings.MigrationPlanner = @()
    }

    $baseSettings | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $baseSettingsPath -Encoding utf8
}

function Get-DefaultDomainNamingContext {
    try {
        $rootDse = New-Object DirectoryServices.DirectoryEntry('LDAP://RootDSE')
        $domainDn = [string]$rootDse.Properties['defaultNamingContext'].Value
        if ([string]::IsNullOrWhiteSpace($domainDn)) {
            throw "defaultNamingContext bos."
        }

        return $domainDn
    }
    catch {
        throw "AD defaultNamingContext cozulemedi. Sunucunun domain uyeligini ve LDAP erisimini kontrol edin. $($_.Exception.Message)"
    }
}

function Resolve-DomainRidAccount {
    param([Parameter(Mandatory)][ValidateRange(1, 999999999)][int]$Rid)

    try {
        $domainDn = Get-DefaultDomainNamingContext

        $domainEntry = New-Object DirectoryServices.DirectoryEntry("LDAP://$domainDn")
        $domainSidBytes = [byte[]]$domainEntry.Properties['objectSid'].Value
        $domainSid = New-Object Security.Principal.SecurityIdentifier($domainSidBytes, 0)
        $accountSid = New-Object Security.Principal.SecurityIdentifier("$($domainSid.Value)-$Rid")
        return @{
            Name = $accountSid.Translate([Security.Principal.NTAccount]).Value
            Sid = $accountSid
        }
    }
    catch {
        throw "Domain hesabi RID $Rid ile cozulemedi. Domain baglantisini kontrol edin. $($_.Exception.Message)"
    }
}

function Resolve-DomainComputersAccount {
    param([string]$ExplicitAccount)

    if (-not [string]::IsNullOrWhiteSpace($ExplicitAccount)) {
        $sid = Resolve-AccountSid -AccountName $ExplicitAccount
        return @{
            Name = $sid.Translate([Security.Principal.NTAccount]).Value
            Sid = $sid
        }
    }

    try {
        return Resolve-DomainRidAccount -Rid 515
    }
    catch {
        throw "Domain Computers grubu RID 515 ile cozulemedi. Domain baglantisini kontrol edin veya -DomainComputersGroup 'DOMAIN\grup' belirtin. $($_.Exception.Message)"
    }
}

function Resolve-ServiceIdentity {
    $selectedCount = @(
        -not [string]::IsNullOrWhiteSpace($GmsaAccount)
        $null -ne $ServiceCredential
        [bool]$AllowLocalSystem
        -not [string]::IsNullOrWhiteSpace($existingServiceAccountToPreserve)
    ).Where({ $_ }).Count

    if ($selectedCount -ne 1) {
        throw "Tam olarak bir servis kimligi secilmelidir: -GmsaAccount, -ServiceCredential veya acik risk kabuluyla -AllowLocalSystem."
    }

    if (-not [string]::IsNullOrWhiteSpace($GmsaAccount)) {
        if ($GmsaAccount -notmatch '^[^\\]+\\[^\\]+\$$') {
            throw "GmsaAccount 'DOMAIN\hesap$' biciminde ve sonunda `$ olacak sekilde verilmelidir."
        }

        $sid = Resolve-AccountSid -AccountName $GmsaAccount
        $testCommand = Get-Command Test-ADServiceAccount -ErrorAction SilentlyContinue
        if ($testCommand) {
            $shortName = ($GmsaAccount.Split('\')[-1]).TrimEnd('$')
            if (-not (Test-ADServiceAccount -Identity $shortName)) {
                throw "gMSA bu sunucuda kullanilamiyor: '$GmsaAccount'. Install-ADServiceAccount ve PrincipalsAllowedToRetrieveManagedPassword ayarlarini kontrol edin."
            }
        }
        else {
            Write-Warning "ActiveDirectory modulu bulunamadigi icin Test-ADServiceAccount calistirilamadi. SCM servis baslatma asamasinda gMSA'yi dogrulayacak."
        }

        return @{
            Type = 'gMSA'
            ScAccount = $GmsaAccount
            SpnAccount = $GmsaAccount
            AclSid = $sid
            ShareAccount = $sid.Translate([Security.Principal.NTAccount]).Value
        }
    }

    if ($null -ne $ServiceCredential) {
        $userName = $ServiceCredential.UserName
        if ($userName -notmatch '^[^\\]+\\[^\\]+$' -or $userName.StartsWith('.\')) {
            throw "ServiceCredential bir domain hesabi olmali ve 'DOMAIN\kullanici' biciminde verilmelidir."
        }

        $sid = Resolve-AccountSid -AccountName $userName
        return @{
            Type = 'Credential'
            ScAccount = $userName
            SpnAccount = $userName
            AclSid = $sid
            ShareAccount = $sid.Translate([Security.Principal.NTAccount]).Value
        }
    }

    if (-not [string]::IsNullOrWhiteSpace($existingServiceAccountToPreserve)) {
        $sid = Resolve-AccountSid -AccountName $existingServiceAccountToPreserve
        return @{
            Type = 'ExistingCredential'
            ScAccount = $existingServiceAccountToPreserve
            SpnAccount = $existingServiceAccountToPreserve
            AclSid = $sid
            ShareAccount = $sid.Translate([Security.Principal.NTAccount]).Value
        }
    }

    $localSystemSid = New-Object Security.Principal.SecurityIdentifier('S-1-5-18')
    Write-Warning "LocalSystem acik olarak secildi. Uzak cihaz erisimi yonetim sunucusunun bilgisayar hesabi ile yapilir; gMSA onerilir."
    return @{
        Type = 'LocalSystem'
        ScAccount = 'LocalSystem'
        SpnAccount = "$env:USERDOMAIN\$env:COMPUTERNAME`$"
        AclSid = $localSystemSid
        ShareAccount = $null
    }
}

function New-ManagedDirectoryAcl {
    param(
        [Security.Principal.SecurityIdentifier]$AdministratorsSid,
        [Security.Principal.SecurityIdentifier]$SystemSid,
        [Security.Principal.SecurityIdentifier]$ServiceSid,
        [string]$ServiceRights,
        [Security.Principal.SecurityIdentifier]$AdditionalReadSid
    )

    $acl = New-Object Security.AccessControl.DirectorySecurity
    $acl.SetAccessRuleProtection($true, $false)
    $inheritance = [Security.AccessControl.InheritanceFlags]'ContainerInherit, ObjectInherit'
    $none = [Security.AccessControl.PropagationFlags]::None
    $allow = [Security.AccessControl.AccessControlType]::Allow

    $null = $acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($SystemSid, 'FullControl', $inheritance, $none, $allow)))
    $null = $acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($AdministratorsSid, 'FullControl', $inheritance, $none, $allow)))
    $null = $acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($ServiceSid, $ServiceRights, $inheritance, $none, $allow)))
    if ($null -ne $AdditionalReadSid -and $AdditionalReadSid.Value -ne $ServiceSid.Value) {
        $null = $acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($AdditionalReadSid, 'ReadAndExecute', $inheritance, $none, $allow)))
    }

    return $acl
}

function Set-ManagedDirectoryAcl {
    param(
        [string]$Path,
        [Security.Principal.SecurityIdentifier]$AdministratorsSid,
        [Security.Principal.SecurityIdentifier]$SystemSid,
        [Security.Principal.SecurityIdentifier]$ServiceSid,
        [string]$ServiceRights,
        [Security.Principal.SecurityIdentifier]$AdditionalReadSid
    )

    $acl = New-ManagedDirectoryAcl `
        -AdministratorsSid $AdministratorsSid `
        -SystemSid $SystemSid `
        -ServiceSid $ServiceSid `
        -ServiceRights $ServiceRights `
        -AdditionalReadSid $AdditionalReadSid
    Set-DirectoryAcl -Path $Path -Acl $acl
}

function New-DirectoryWithAcl {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][Security.AccessControl.DirectorySecurity]$Acl
    )

    $directoryInfo = New-Object IO.DirectoryInfo($Path)
    $aclOverload = [IO.DirectoryInfo].GetMethods() |
        Where-Object {
            $_.Name -eq 'Create' -and
            $_.GetParameters().Count -eq 1 -and
            $_.GetParameters()[0].ParameterType -eq [Security.AccessControl.DirectorySecurity]
        } |
        Select-Object -First 1
    if ($null -ne $aclOverload) {
        $directoryInfo.Create($Acl)
        return
    }

    [IO.FileSystemAclExtensions]::CreateDirectory($Acl, $Path) | Out-Null
}

function Set-DirectoryAcl {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][Security.AccessControl.DirectorySecurity]$Acl
    )

    $directoryInfo = New-Object IO.DirectoryInfo($Path)
    $setAclMethod = [IO.DirectoryInfo].GetMethods() |
        Where-Object {
            $_.Name -eq 'SetAccessControl' -and
            $_.GetParameters().Count -eq 1 -and
            $_.GetParameters()[0].ParameterType -eq [Security.AccessControl.DirectorySecurity]
        } |
        Select-Object -First 1
    if ($null -ne $setAclMethod) {
        $directoryInfo.SetAccessControl($Acl)
        return
    }

    [IO.FileSystemAclExtensions]::SetAccessControl($directoryInfo, $Acl)
}

function Initialize-ManagedDirectory {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][Security.Principal.SecurityIdentifier]$AdministratorsSid,
        [Parameter(Mandatory)][Security.Principal.SecurityIdentifier]$SystemSid,
        [Parameter(Mandatory)][Security.Principal.SecurityIdentifier]$ServiceSid,
        [Parameter(Mandatory)][string]$ServiceRights,
        [Security.Principal.SecurityIdentifier]$AdditionalReadSid
    )

    $parent = Split-Path $Path -Parent
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        Assert-NoReparsePointInPath -Path $parent
    }
    $acl = New-ManagedDirectoryAcl `
        -AdministratorsSid $AdministratorsSid `
        -SystemSid $SystemSid `
        -ServiceSid $ServiceSid `
        -ServiceRights $ServiceRights `
        -AdditionalReadSid $AdditionalReadSid
    if (Test-Path -LiteralPath $Path) {
        Assert-NoReparsePointInPath -Path $Path
        Set-DirectoryAcl -Path $Path -Acl $acl
    }
    else {
        New-DirectoryWithAcl -Path $Path -Acl $acl
    }
    Assert-NoReparsePointInPath -Path $Path
    Set-DirectoryAcl -Path $Path -Acl $acl
}

function Ensure-CollectorShare {
    param(
        [string]$Name,
        [string]$Path,
        [string]$AdministratorsAccount,
        [string[]]$ReadAccounts
    )

    $existingShare = Get-SmbShare -Name $Name -ErrorAction SilentlyContinue
    if ($existingShare) {
        $existingPath = [IO.Path]::GetFullPath($existingShare.Path).TrimEnd('\')
        $requestedPath = [IO.Path]::GetFullPath($Path).TrimEnd('\')
        if (-not $existingPath.Equals($requestedPath, [StringComparison]::OrdinalIgnoreCase)) {
            throw "SMB share '$Name' zaten farkli bir path kullaniyor: '$existingPath'. Guvenlik nedeniyle otomatik degistirilmedi."
        }
    }
    else {
        New-SmbShare -Name $Name -Path $Path -FullAccess $AdministratorsAccount -ReadAccess $ReadAccounts -FolderEnumerationMode AccessBased | Out-Null
    }

    Grant-SmbShareAccess -Name $Name -AccountName $AdministratorsAccount -AccessRight Full -Force | Out-Null
    foreach ($account in $ReadAccounts | Select-Object -Unique) {
        Grant-SmbShareAccess -Name $Name -AccountName $account -AccessRight Read -Force | Out-Null
    }

    foreach ($sidValue in @('S-1-1-0', 'S-1-5-32-546')) {
        try {
            $unsafeAccount = Resolve-AccountNameBySid -SidValue $sidValue
            Revoke-SmbShareAccess -Name $Name -AccountName $unsafeAccount -Force -ErrorAction SilentlyContinue | Out-Null
        }
        catch {
            Write-Verbose "SMB ACE temizleme atlandi: $sidValue"
        }
    }
}

function Invoke-ServiceControl([string[]]$Arguments) {
    $output = & "$env:SystemRoot\System32\sc.exe" @Arguments 2>&1
    if ($LASTEXITCODE -ne 0) {
        $safeArguments = @($Arguments)
        $passwordIndex = [Array]::IndexOf($safeArguments, 'password=')
        if ($passwordIndex -ge 0 -and ($passwordIndex + 1) -lt $safeArguments.Count) {
            $safeArguments[$passwordIndex + 1] = '<redacted>'
        }
        throw "sc.exe basarisiz oldu: sc.exe $($safeArguments -join ' '). Cikti: $($output -join ' ')"
    }
}

function Configure-Service {
    param(
        [string]$Name,
        [string]$BinPath,
        [hashtable]$Identity
    )

    $existing = Get-Service -Name $Name -ErrorAction SilentlyContinue
    if ($Identity.Type -eq 'ExistingCredential') {
        if (-not $existing) {
            throw 'Korunacak mevcut servis kimligi secildi ancak servis bulunamadi.'
        }
        Invoke-ServiceControl -Arguments @('config', $Name, 'start=', 'delayed-auto', 'binPath=', $BinPath, 'DisplayName=', $Name)
    }
    elseif ($Identity.Type -eq 'Credential') {
        if ($existing) {
            $escapedName = $Name.Replace("'", "''")
            $cimService = Get-CimInstance -ClassName Win32_Service -Filter "Name='$escapedName'"
            if ($null -eq $cimService) {
                throw "Mevcut servis CIM uzerinden bulunamadi: '$Name'."
            }

            $passwordPointer = [IntPtr]::Zero
            $plainPassword = $null
            try {
                $passwordPointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($ServiceCredential.Password)
                $plainPassword = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($passwordPointer)
                $changeResult = Invoke-CimMethod -InputObject $cimService -MethodName Change -Arguments @{
                    DisplayName = $Name
                    PathName = $BinPath
                    StartMode = 'Automatic'
                    StartName = $Identity.ScAccount
                    StartPassword = $plainPassword
                }
                if ($changeResult.ReturnValue -ne 0) {
                    throw "Win32_Service.Change hata kodu dondurdu: $($changeResult.ReturnValue)."
                }
            }
            finally {
                $plainPassword = $null
                if ($passwordPointer -ne [IntPtr]::Zero) {
                    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($passwordPointer)
                }
            }
        }
        else {
            New-Service -Name $Name -BinaryPathName $BinPath -DisplayName $Name -StartupType Automatic -Credential $ServiceCredential | Out-Null
        }

        Invoke-ServiceControl -Arguments @('config', $Name, 'start=', 'delayed-auto', 'binPath=', $BinPath, 'DisplayName=', $Name)
    }
    else {
        $operation = if ($existing) { 'config' } else { 'create' }
        Invoke-ServiceControl -Arguments @(
            $operation,
            $Name,
            'binPath=', $BinPath,
            'start=', 'delayed-auto',
            'DisplayName=', $Name,
            'obj=', $Identity.ScAccount
        )
    }

    Invoke-ServiceControl -Arguments @('failure', $Name, 'reset=', '86400', 'actions=', 'restart/5000/restart/15000/restart/60000')
    Invoke-ServiceControl -Arguments @('failureflag', $Name, '1')
    Invoke-ServiceControl -Arguments @('description', $Name, 'O365 PST migration inventory and audit service')
}

function Ensure-EventLogSource {
    param(
        [Parameter(Mandatory)][string]$SourceName,
        [string]$LogName = 'Application'
    )

    # Creating the source needs HKLM write access, which a gMSA service identity does not have, and
    # Microsoft.Extensions.Logging.EventLog disables itself after the first failed write instead of
    # throwing -- so the source has to exist before the service identity ever changes.
    try {
        # SourceExists enumerates every log including Security and throws when one is unreadable, so a
        # failure here means "unknown", not "missing"; creation is still attempted below.
        if ([Diagnostics.EventLog]::SourceExists($SourceName)) {
            Write-Verbose "Event log source zaten mevcut: '$SourceName'."
            return
        }
    }
    catch {
        Write-Verbose "Event log source varligi dogrulanamadi: '$SourceName'. $($_.Exception.Message)"
    }

    try {
        # New-EventLog is absent from some PowerShell 7 installations; the framework call is always there.
        if (Get-Command New-EventLog -ErrorAction SilentlyContinue) {
            New-EventLog -LogName $LogName -Source $SourceName -ErrorAction Stop
        }
        else {
            [Diagnostics.EventLog]::CreateEventSource($SourceName, $LogName)
        }

        Write-Host "Event log source olusturuldu: $LogName / $SourceName" -ForegroundColor DarkCyan
    }
    catch {
        Write-Warning ("Event log source '$SourceName' olusturulamadi (zaten kayitli olabilir); deployment devam ediyor. " +
                       "Kaynak yoksa ve servis kimligi yerel yonetici degilse Warning+ kayitlari sessizce dusecektir. " +
                       "$($_.Exception.Message)")
    }
}

function Write-DeploymentFailureDiagnostics {
    param(
        [Parameter(Mandatory)][string]$FailedAppDir,
        [Parameter(Mandatory)][string]$StagingAppDir
    )

    # BURCUDC: rollback moved the application into .failed-<id> while the documented recovery command
    # still pointed at <InstallRoot>\app, so the operator could only reproduce a "path not found".
    # Print the directory that actually exists together with the command that runs it.
    $diagnosticDir = ''
    if (Test-Path -LiteralPath $FailedAppDir -PathType Container) {
        $diagnosticDir = $FailedAppDir
        Write-Warning "Deployment geri alindi. Basarisiz surum bu dizinde saklandi: $FailedAppDir"
    }
    elseif (Test-Path -LiteralPath $StagingAppDir -PathType Container) {
        $diagnosticDir = $StagingAppDir
        Write-Warning "Deployment canliya alinmadan durdu. Hazirlanan surum bu dizinde: $StagingAppDir"
    }

    if ([string]::IsNullOrWhiteSpace($diagnosticDir)) {
        Write-Warning "Basarisiz surum dizini bulunamadi. Event Viewer > Windows Logs > Application (source: O365AuditTool, .NET Runtime) kayitlarina bakin."
        return
    }

    $runCommand = if (Test-Path -LiteralPath (Join-Path $diagnosticDir 'O365AuditTool.exe') -PathType Leaf) {
        '.\O365AuditTool.exe --environment Production'
    }
    else {
        'dotnet .\O365AuditTool.dll --environment Production'
    }

    $quotedDir = $diagnosticDir.Replace("'", "''")
    Write-Host "Baslangic hatasini interaktif tekrar uretmek icin (elevated PowerShell):" -ForegroundColor Yellow
    Write-Host "    Push-Location '$quotedDir'; $runCommand; Pop-Location" -ForegroundColor Yellow
    Write-Host "Uygulama appsettings.Production.json dosyasini calisma dizininden okur; Push-Location zorunludur." -ForegroundColor DarkYellow
    Write-Host "Event Viewer kayitlari: Get-WinEvent -LogName Application -MaxEvents 40 | Where-Object { `$_.ProviderName -in @('O365AuditTool', '.NET Runtime', 'Application Error') } | Format-List TimeCreated, ProviderName, Message" -ForegroundColor DarkYellow
}

if ($FunctionsOnly) { return }

Assert-Admin

$repoRoot = if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) {
    ''
}
else {
    Split-Path $PSScriptRoot -Parent
}

$usingPublishedBundle = -not [string]::IsNullOrWhiteSpace($PublishedAppPath)
if ($usingPublishedBundle) {
    $PublishedAppPath = [IO.Path]::GetFullPath($PublishedAppPath)
    if (-not (Test-Path -LiteralPath $PublishedAppPath -PathType Container)) {
        throw "PublishedAppPath gecersiz veya erisilemiyor: '$PublishedAppPath'."
    }

    $publishedExe = Join-Path $PublishedAppPath 'O365AuditTool.exe'
    $publishedDll = Join-Path $PublishedAppPath 'O365AuditTool.dll'
    if (
        -not (Test-Path -LiteralPath $publishedExe -PathType Leaf) -and
        -not (Test-Path -LiteralPath $publishedDll -PathType Leaf)
    ) {
        throw "PublishedAppPath uygulama binary'si icermiyor: '$PublishedAppPath'."
    }
    Assert-NoReparsePointInPath -Path $PublishedAppPath
}
else {
    if (-not $SkipPublish) {
        if ([string]::IsNullOrWhiteSpace($ProjectPath)) {
            if ([string]::IsNullOrWhiteSpace($repoRoot)) {
                throw "ProjectPath zorunludur. Bootstrap kurulumunda PublishedAppPath kullanin."
            }
            $ProjectPath = Join-Path $repoRoot 'src\O365AuditTool'
        }

        $ProjectPath = [IO.Path]::GetFullPath($ProjectPath)
        $csprojPath = Join-Path $ProjectPath 'O365AuditTool.csproj'
        if (-not (Test-Path -LiteralPath $csprojPath -PathType Leaf)) {
            throw "ProjectPath gecersiz: '$ProjectPath'. O365AuditTool.csproj bulunamadi."
        }
    }
}

if (-not [string]::IsNullOrWhiteSpace($CollectorPath)) {
    $CollectorPath = [IO.Path]::GetFullPath($CollectorPath)
    if (-not (Test-Path -LiteralPath $CollectorPath -PathType Leaf)) {
        throw "CollectorPath gecersiz veya erisilemiyor: '$CollectorPath'."
    }
    Assert-NoReparsePointInPath -Path $CollectorPath
}

$InstallRoot = [IO.Path]::GetFullPath($InstallRoot)
$existingProductionSettings = $null
$existingSettingsPath = Join-Path $InstallRoot 'app\appsettings.Production.json'
if ($AutoConfigure -and (Test-Path -LiteralPath $existingSettingsPath -PathType Leaf)) {
    try {
        $existingProductionSettings = Get-Content -LiteralPath $existingSettingsPath -Raw | ConvertFrom-Json
        Write-Host "Mevcut production ayarlari upgrade icin korunacak: '$existingSettingsPath'." -ForegroundColor Cyan
    }
    catch {
        throw "Mevcut production ayarlari okunamadi; guvenli upgrade durduruldu: '$existingSettingsPath'. $($_.Exception.Message)"
    }
}

$effectiveArtifactCopyEnabled = [bool]$EnableArtifactCopy
$effectiveCopyVerifySha256 = -not [bool]$DisableCopySha256
if ($null -ne $existingProductionSettings) {
    if (-not $PSBoundParameters.ContainsKey('Port')) {
        $Port = [int](Get-ObjectPathValue $existingProductionSettings @('Server', 'HttpsPort') $Port)
    }
    if (-not $PSBoundParameters.ContainsKey('HealthPort')) {
        $HealthPort = [int](Get-ObjectPathValue $existingProductionSettings @('Server', 'HealthPort') $HealthPort)
    }
    if (-not $PSBoundParameters.ContainsKey('DashboardDnsName')) {
        $DashboardDnsName = [string](Get-ObjectPathValue $existingProductionSettings @('Server', 'PublicDnsName') $DashboardDnsName)
    }
    if (-not $PSBoundParameters.ContainsKey('TlsCertificateThumbprint')) {
        $TlsCertificateThumbprint = [string](Get-ObjectPathValue $existingProductionSettings @('Server', 'TlsCertificateThumbprint') $TlsCertificateThumbprint)
    }
    if (-not $PSBoundParameters.ContainsKey('AllowInsecureHttpDashboard')) {
        $AllowInsecureHttpDashboard = [bool](Get-ObjectPathValue $existingProductionSettings @('Server', 'AllowInsecureHttp') $false)
    }
    if (-not $PSBoundParameters.ContainsKey('DefaultOuFilter')) {
        $DefaultOuFilter = [string](Get-ObjectPathValue $existingProductionSettings @('Collector', 'DefaultOuFilter') $DefaultOuFilter)
    }
    if (-not $PSBoundParameters.ContainsKey('DefaultSiteFilter')) {
        $DefaultSiteFilter = [string](Get-ObjectPathValue $existingProductionSettings @('Collector', 'DefaultSiteFilter') $DefaultSiteFilter)
    }
    if (-not $PSBoundParameters.ContainsKey('FallbackTargets')) {
        $FallbackTargets = @(Get-ObjectPathValue $existingProductionSettings @('Collector', 'FallbackTargets') @())
    }
    if (-not $PSBoundParameters.ContainsKey('ExcludeDeviceNames')) {
        $ExcludeDeviceNames = @(Get-ObjectPathValue $existingProductionSettings @('Collector', 'ExcludeDeviceNames') @())
    }
    if (-not $PSBoundParameters.ContainsKey('ExcludeOus')) {
        $ExcludeOus = @(Get-ObjectPathValue $existingProductionSettings @('Collector', 'ExcludeOus') @())
    }
    if (-not $script:ExcludeUnknownOperatingSystemExplicitlySupplied) {
        $ExcludeUnknownOperatingSystem = [bool](Get-ObjectPathValue $existingProductionSettings @('Collector', 'ExcludeUnknownOperatingSystem') $false)
    }
    if (-not $PSBoundParameters.ContainsKey('CollectorShareName')) {
        $existingRemoteScriptPath = [string](Get-ObjectPathValue $existingProductionSettings @('Collector', 'RemoteScriptPath') '')
        if ($existingRemoteScriptPath -match '^\\\\[^\\]+\\([^\\]+)\\') {
            $CollectorShareName = $Matches[1]
        }
    }
    if (-not $PSBoundParameters.ContainsKey('CollectorSharePath') -and -not [string]::IsNullOrWhiteSpace($CollectorShareName)) {
        $existingCollectorShare = Get-SmbShare -Name $CollectorShareName -ErrorAction SilentlyContinue
        if ($null -ne $existingCollectorShare) {
            $CollectorSharePath = [string]$existingCollectorShare.Path
        }
    }
    if (-not $PSBoundParameters.ContainsKey('AuditAdminGroups')) {
        $AuditAdminGroups = @(Get-ObjectPathValue $existingProductionSettings @('Auth', 'RoleMappings', 'AuditAdmin') @())
    }
    if (-not $PSBoundParameters.ContainsKey('AuditReaderGroups')) {
        $AuditReaderGroups = @(Get-ObjectPathValue $existingProductionSettings @('Auth', 'RoleMappings', 'AuditReader') @())
    }
    if (-not $PSBoundParameters.ContainsKey('MigrationPlannerGroups')) {
        $MigrationPlannerGroups = @(Get-ObjectPathValue $existingProductionSettings @('Auth', 'RoleMappings', 'MigrationPlanner') @())
    }
    if (-not $EnableArtifactCopy -and -not $DisableArtifactCopy) {
        $effectiveArtifactCopyEnabled = [bool](Get-ObjectPathValue $existingProductionSettings @('Copy', 'Enabled') $false)
    }
    if (-not $PSBoundParameters.ContainsKey('CopyTargetRoot')) {
        $CopyTargetRoot = [string](Get-ObjectPathValue $existingProductionSettings @('Copy', 'DefaultTargetRoot') $CopyTargetRoot)
    }
    if (-not $PSBoundParameters.ContainsKey('AllowedCopyTargetRoots')) {
        $AllowedCopyTargetRoots = @(Get-ObjectPathValue $existingProductionSettings @('Copy', 'AllowedTargetRoots') @())
    }
    if (-not $PSBoundParameters.ContainsKey('AllowedCopySourceUncRoots')) {
        $AllowedCopySourceUncRoots = @(Get-ObjectPathValue $existingProductionSettings @('Copy', 'AllowedSourceUncRoots') @())
    }
    if (-not $CopyVerifySha256 -and -not $DisableCopySha256) {
        $effectiveCopyVerifySha256 = [bool](Get-ObjectPathValue $existingProductionSettings @('Copy', 'VerifySha256') $true)
    }

    $identityWasProvided =
        -not [string]::IsNullOrWhiteSpace($GmsaAccount) -or
        $null -ne $ServiceCredential -or
        [bool]$AllowLocalSystem
    if (-not $identityWasProvided) {
        $escapedServiceName = $ServiceName.Replace("'", "''")
        $existingCimService = Get-CimInstance -ClassName Win32_Service -Filter "Name='$escapedServiceName'" -ErrorAction SilentlyContinue
        if ($null -ne $existingCimService) {
            $existingStartName = [string]$existingCimService.StartName
            if ($existingStartName -match '^[^\\]+\\[^\\]+\$$') {
                $GmsaAccount = $existingStartName
            }
            elseif ($existingStartName -in @('LocalSystem', 'NT AUTHORITY\SYSTEM')) {
                $AllowLocalSystem = $true
            }
            elseif (-not [string]::IsNullOrWhiteSpace($existingStartName)) {
                $existingServiceAccountToPreserve = $existingStartName
            }
        }
    }
}
if ($DisableArtifactCopy) {
    $effectiveArtifactCopyEnabled = $false
}
if ([string]::IsNullOrWhiteSpace($CollectorSharePath)) {
    $CollectorSharePath = Join-Path $InstallRoot 'share'
}
$CollectorSharePath = [IO.Path]::GetFullPath($CollectorSharePath)
if ($Port -eq $HealthPort) {
    throw 'Port ve HealthPort farkli olmalidir.'
}
if ([IO.Path]::GetPathRoot($InstallRoot).TrimEnd('\') -eq $InstallRoot.TrimEnd('\')) {
    throw "InstallRoot bir surucu kok dizini olamaz: '$InstallRoot'."
}
if (-not (Test-PathWithinRoot -Path $CollectorSharePath.TrimEnd('\') -Root $InstallRoot.TrimEnd('\'))) {
    throw "CollectorSharePath InstallRoot altinda olmalidir; yonetilmeyen dizinlerin ACL'leri degistirilmez: '$CollectorSharePath'."
}
if ($CollectorShareName -notmatch '^[A-Za-z0-9_-]+$') {
    throw "CollectorShareName yalnizca harf, rakam, alt cizgi ve tire icerebilir."
}
if ($ServiceName -notmatch '^[A-Za-z0-9_.-]+$') {
    throw "ServiceName yalnizca harf, rakam, nokta, alt cizgi ve tire icerebilir."
}

Ensure-EventLogSource -SourceName $eventLogSourceName

$dotnet = $null
if (-not $usingPublishedBundle -and -not $SkipPublish) {
    $dotnet = Resolve-DotNetPath -Publishing $true
    Assert-DotNet10 -DotNetPath $dotnet -Publishing $true
}
Assert-PsExec -Path $PsExecPath -AllowUnsigned $AllowUnsignedPsExec.IsPresent
$psExecSourceHash = (Get-FileHash -LiteralPath $PsExecPath -Algorithm SHA256).Hash.ToUpperInvariant()

if ($AutoConfigure) {
    $selectedIdentityCount = @(
        -not [string]::IsNullOrWhiteSpace($GmsaAccount)
        $null -ne $ServiceCredential
        [bool]$AllowLocalSystem
        -not [string]::IsNullOrWhiteSpace($existingServiceAccountToPreserve)
    ).Where({ $_ }).Count
    if ($selectedIdentityCount -eq 0) {
        $AllowLocalSystem = $true
        Write-Warning 'AutoConfigure servis kimligi verilmedigi icin LocalSystem sececek. Endpoint uzak yonetim yetkisi yonetim sunucusunun bilgisayar hesabina verilmelidir.'
    }

    if (
        @($AuditAdminGroups | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count -eq 0 -or
        @($AuditReaderGroups | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count -eq 0 -or
        @($MigrationPlannerGroups | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count -eq 0
    ) {
        $domainAdmins = Resolve-DomainRidAccount -Rid 512
        if (@($AuditAdminGroups | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count -eq 0) {
            $AuditAdminGroups = @($domainAdmins.Name)
        }
        if (@($AuditReaderGroups | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count -eq 0) {
            $AuditReaderGroups = @($domainAdmins.Name)
        }
        if (@($MigrationPlannerGroups | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count -eq 0) {
            $MigrationPlannerGroups = @($domainAdmins.Name)
        }
        Write-Warning "AutoConfigure eksik RBAC rollerini '$($domainAdmins.Name)' grubuna bagladi. Kurulum sonrasi ayrik least-privilege gruplarla degistirin."
    }

}

# The scope guard runs on EVERY deploy, not only under -AutoConfigure. An empty DefaultOuFilter is not
# "unset" to the service: ActiveDirectoryTargetProvider applies no OU restriction at all for a blank
# filter, which enumerates exactly the same objects as the domain root. Leaving the guard inside the
# -AutoConfigure branch would keep the whole-domain scan reachable through the documented explicit-parameter
# path in docs/DEPLOYMENT-DC.md.
if ([string]::IsNullOrWhiteSpace($DefaultOuFilter) -and [string]::IsNullOrWhiteSpace($DefaultSiteFilter)) {
    $domainRootHint = ''
    try {
        $domainRootHint = " ('" + (Get-DefaultDomainNamingContext) + "')"
    }
    catch {
        Write-Verbose "Domain naming context hata mesaji icin cozulemedi."
    }

    throw ("Deployment tarama kapsamini kendisi belirleyemez: -DefaultOuFilter veya -DefaultSiteFilter zorunludur. " +
           "Bos kapsam domain kokuyle$domainRootHint ayni sonucu verir ve sunuculari, domain controller'i, DMZ " +
           "makinelerini ve domain'e katilmis NAS/appliance cihazlarini her gece taramaya sokar. " +
           "Yalnizca is istasyonu OU'sunu verin, ornek: -DefaultOuFilter 'OU=PC,OU=NBR,DC=nbr,DC=local'. " +
           "Mevcut OU'lari 'Get-ADOrganizationalUnit -Filter * | Select-Object DistinguishedName' ile listeleyebilirsiniz.")
}

if (-not [string]::IsNullOrWhiteSpace($DefaultOuFilter)) {
    try {
        $domainNamingContext = Get-DefaultDomainNamingContext
        if ($DefaultOuFilter.Trim().Equals($domainNamingContext, [StringComparison]::OrdinalIgnoreCase)) {
            Write-Warning ("Tarama kapsami domain koku: '$DefaultOuFilter'. Bu kapsam sunuculari, domain " +
                           "controller'i ve domain'e katilmis appliance'lari da her gece tarar. -DefaultOuFilter ile " +
                           "is istasyonu OU'suna daraltin veya -ExcludeOus / -ExcludeDeviceNames ile haric tutun.")
        }
    }
    catch {
        Write-Verbose "Domain naming context karsilastirmasi yapilamadi."
    }
}

$serviceIdentity = Resolve-ServiceIdentity
$resolvedDashboardDnsName = Resolve-DashboardDnsName -ExplicitName $DashboardDnsName
if ($AutoConfigure) {
    try {
        Set-LocalBrowserSsoPolicy -ServerName $resolvedDashboardDnsName
    }
    catch {
        Write-Warning "Yerel browser SSO policy ayarlanamadi; deployment devam edecek. GPO ile AuthServerAllowlist ve Local Intranet zone ayarlayin. $($_.Exception.Message)"
    }
}
$resolvedTlsCertificateThumbprint = Resolve-TlsCertificateThumbprint `
    -Thumbprint $TlsCertificateThumbprint `
    -AllowInsecure $AllowInsecureHttpDashboard.IsPresent `
    -DnsName $resolvedDashboardDnsName `
    -AutoConfigure $AutoConfigure.IsPresent
if (-not $AllowInsecureHttpDashboard) {
    Ensure-HttpSpns -AccountName $serviceIdentity.SpnAccount -DnsName $resolvedDashboardDnsName
    Ensure-TlsPrivateKeyAccess `
        -Thumbprint $resolvedTlsCertificateThumbprint `
        -Identity $serviceIdentity
}
$resolvedAuditAdminGroups = @(Resolve-DomainGroupList -RoleName 'AuditAdmin' -GroupNames $AuditAdminGroups)
$resolvedAuditReaderGroups = @(Resolve-DomainGroupList -RoleName 'AuditReader' -GroupNames $AuditReaderGroups)
$resolvedMigrationPlannerGroups = @(Resolve-DomainGroupList -RoleName 'MigrationPlanner' -GroupNames $MigrationPlannerGroups)
$resolvedFallbackTargets = @(Resolve-FallbackTargets -Targets $FallbackTargets)
$resolvedExcludeDeviceNames = @(Resolve-ExcludeDeviceNames -Names $ExcludeDeviceNames)
$resolvedExcludeOus = @(Resolve-ExcludeOus -OrganizationalUnits $ExcludeOus)
$resolvedCopyTargetRoot = Resolve-CopyRoot -Path $CopyTargetRoot -ParameterName 'CopyTargetRoot' -AllowEmpty
$resolvedAllowedCopyTargetRoots = @(
    $AllowedCopyTargetRoots |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        ForEach-Object { Resolve-CopyRoot -Path $_ -ParameterName 'AllowedCopyTargetRoots' } |
        Select-Object -Unique
)
$resolvedAllowedCopySourceUncRoots = @(
    @(
        foreach ($sourceRoot in ($AllowedCopySourceUncRoots | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })) {
            $resolvedSourceRoot = Resolve-CopyRoot -Path $sourceRoot -ParameterName 'AllowedCopySourceUncRoots'
            if ($resolvedSourceRoot -notlike '\\*') {
                throw "AllowedCopySourceUncRoots yalnizca UNC kokleri kabul eder: '$resolvedSourceRoot'."
            }
            $resolvedSourceRoot
        }
    ) | Select-Object -Unique
)

if ($effectiveArtifactCopyEnabled) {
    if ([string]::IsNullOrWhiteSpace($resolvedCopyTargetRoot)) {
        throw "Artifact copy etkinlestirilemez: -CopyTargetRoot zorunludur."
    }
    if ($resolvedAllowedCopyTargetRoots.Count -eq 0) {
        throw "Artifact copy etkinlestirilemez: -AllowedCopyTargetRoots en az bir guvenli kok icermelidir."
    }
    if (-not ($resolvedAllowedCopyTargetRoots | Where-Object { Test-PathWithinRoot -Path $resolvedCopyTargetRoot -Root $_ })) {
        throw "CopyTargetRoot izin verilen koklerden birinin altinda degil: '$resolvedCopyTargetRoot'."
    }
    if (-not (Test-Path -LiteralPath $resolvedCopyTargetRoot -PathType Container)) {
        throw "CopyTargetRoot mevcut degil veya deployment hesabi tarafindan erisilemiyor: '$resolvedCopyTargetRoot'. Hedef dizini ve SMB/NTFS izinlerini once hazirlayin."
    }

    Write-Warning "Artifact copy etkin. Servis kimligi '$($serviceIdentity.ScAccount)' tum kaynak cihazlarda ADMIN$ okuma ve hedef '$resolvedCopyTargetRoot' uzerinde dosya olusturma/yazma yetkisine sahip olmalidir. Deployment hesabi ile yapilan path kontrolu servis kimliginin etkin yetkilerini dogrulamaz."
    if ($serviceIdentity.Type -eq 'LocalSystem') {
        Write-Warning "LocalSystem ile copy erisimi '$env:USERDOMAIN\$env:COMPUTERNAME`$' bilgisayar hesabi uzerinden yapilir. Kaynak ADMIN$ ve hedef share izinlerini bu hesap icin acmak yerine sinirli bir gMSA kullanilmasi onerilir."
    }
}

$domainComputers = Resolve-DomainComputersAccount -ExplicitAccount $DomainComputersGroup
$administratorsSid = New-Object Security.Principal.SecurityIdentifier('S-1-5-32-544')
$administratorsName = $administratorsSid.Translate([Security.Principal.NTAccount]).Value
$systemSid = New-Object Security.Principal.SecurityIdentifier('S-1-5-18')

$liveAppDir = Join-Path $InstallRoot 'app'
$deploymentId = [Guid]::NewGuid().ToString('N')
$stagingAppDir = Join-Path $InstallRoot ".staging-$deploymentId"
$rollbackAppDir = Join-Path $InstallRoot ".rollback-$deploymentId"
$failedAppDir = Join-Path $InstallRoot ".failed-$deploymentId"
$appDir = $stagingAppDir
$appDataDir = Join-Path $appDir 'data'
$dataDir = Join-Path $InstallRoot 'data'
$logDir = Join-Path $InstallRoot 'logs'

Assert-NoReparsePointInPath -Path (Split-Path $InstallRoot -Parent)
Initialize-ManagedDirectory -Path $InstallRoot -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'ReadAndExecute'
Initialize-ManagedDirectory -Path $stagingAppDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'ReadAndExecute'
Initialize-ManagedDirectory -Path $appDataDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'Modify'
Initialize-ManagedDirectory -Path $dataDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'Modify'
Initialize-ManagedDirectory -Path $logDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'Modify'
Initialize-ManagedDirectory -Path $CollectorSharePath -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'ReadAndExecute' -AdditionalReadSid $domainComputers.Sid

$existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
$restartOnFailure = $existingService -and $existingService.Status -eq 'Running'
$deploymentSwapped = $false

try {
    if ($usingPublishedBundle) {
        Assert-NoReparsePointTree -Root $PublishedAppPath
        foreach ($publishedItem in (Get-ChildItem -LiteralPath $PublishedAppPath -Force)) {
            Copy-Item -LiteralPath $publishedItem.FullName -Destination $appDir -Recurse -Force
        }
        Assert-DirectoryCopyIntegrity -SourceRoot $PublishedAppPath -DestinationRoot $appDir
    }
    elseif ($SkipPublish) {
        if (-not (Test-Path -LiteralPath $liveAppDir -PathType Container)) {
            throw "SkipPublish yalnizca mevcut bir deployment'i yeniden yapilandirabilir; live app dizini bulunamadi: '$liveAppDir'."
        }
        foreach ($liveItem in (Get-ChildItem -LiteralPath $liveAppDir -Force)) {
            Copy-Item -LiteralPath $liveItem.FullName -Destination $appDir -Recurse -Force
        }
    }
    else {
        Push-Location $ProjectPath
        try {
            & $dotnet publish -c Release -o $appDir
            if ($LASTEXITCODE -ne 0) {
                throw "dotnet publish hata kodu ile tamamlandi: $LASTEXITCODE."
            }
        }
        finally {
            Pop-Location
        }
    }

    $applicationExe = Join-Path $appDir 'O365AuditTool.exe'
    $applicationDll = Join-Path $appDir 'O365AuditTool.dll'
    if (
        -not (Test-Path -LiteralPath $applicationExe -PathType Leaf) -and
        -not (Test-Path -LiteralPath $applicationDll -PathType Leaf)
    ) {
        throw "Uygulama binary'si bulunamadi: '$appDir'. -SkipPublish yalnizca hazir publish cikisi varsa kullanilabilir."
    }
    Remove-PublishedSampleMappings -ApplicationDirectory $appDir

    $managedToolsDir = Join-Path $appDir 'tools'
    New-Item -ItemType Directory -Path $managedToolsDir -Force | Out-Null
    $managedPsExecStagingPath = Join-Path $managedToolsDir 'psexec.exe'
    Copy-Item -LiteralPath $PsExecPath -Destination $managedPsExecStagingPath -Force
    $managedPsExecHash = (Get-FileHash -LiteralPath $managedPsExecStagingPath -Algorithm SHA256).Hash.ToUpperInvariant()
    if (-not $managedPsExecHash.Equals($psExecSourceHash, [StringComparison]::Ordinal)) {
        throw 'Korumali PsExec copy SHA256 dogrulamasi basarisiz.'
    }
    $managedPsExecLivePath = Join-Path $liveAppDir 'tools\psexec.exe'

    $collectorSource = $CollectorPath
    if ([string]::IsNullOrWhiteSpace($collectorSource) -and -not [string]::IsNullOrWhiteSpace($repoRoot)) {
        $collectorSource = Join-Path $repoRoot 'scripts\collector.ps1'
    }
    if (
        [string]::IsNullOrWhiteSpace($collectorSource) -or
        -not (Test-Path -LiteralPath $collectorSource -PathType Leaf)
    ) {
        if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) {
            throw "collector.ps1 bulunamadi. Bundle kurulumunda CollectorPath zorunludur."
        }
        $collectorSource = Join-Path $PSScriptRoot 'collector.ps1'
    }
    if (-not (Test-Path -LiteralPath $collectorSource -PathType Leaf)) {
        throw "collector.ps1 bulunamadi. Beklenen konum: '$repoRoot\scripts\collector.ps1'."
    }

    $collectorDestination = Join-Path $CollectorSharePath 'collector.ps1'
    Copy-Item -LiteralPath $collectorSource -Destination $collectorDestination -Force
    $collectorSourceHash = (Get-FileHash -LiteralPath $collectorSource -Algorithm SHA256).Hash
    $collectorDestinationHash = (Get-FileHash -LiteralPath $collectorDestination -Algorithm SHA256).Hash
    if (-not $collectorSourceHash.Equals($collectorDestinationHash, [StringComparison]::OrdinalIgnoreCase)) {
        throw "collector.ps1 copy SHA256 dogrulamasi basarisiz."
    }

    $diagnosticsSource = Join-Path $PSScriptRoot 'Get-O365AuditDiagnostics.ps1'
    if (Test-Path -LiteralPath $diagnosticsSource -PathType Leaf) {
        Copy-Item -LiteralPath $diagnosticsSource `
            -Destination (Join-Path $InstallRoot 'Get-O365AuditDiagnostics.ps1') `
            -Force
    }

    $shareReaders = @($domainComputers.Name)
    if (-not [string]::IsNullOrWhiteSpace($serviceIdentity.ShareAccount)) {
        $shareReaders += $serviceIdentity.ShareAccount
    }
    Ensure-CollectorShare -Name $CollectorShareName -Path $CollectorSharePath -AdministratorsAccount $administratorsName -ReadAccounts $shareReaders

    $productionSettings = @{
        ConnectionStrings = @{ AuditDb = "Data Source=$dataDir\audit.db;Default Timeout=30;Pooling=True" }
        Server = @{
            HttpsPort = $Port
            HealthPort = $HealthPort
            PublicDnsName = $resolvedDashboardDnsName
            TlsCertificateThumbprint = $resolvedTlsCertificateThumbprint
            AllowInsecureHttp = $AllowInsecureHttpDashboard.IsPresent
        }
        Auth = @{
            RoleMappings = @{
                AuditAdmin = $resolvedAuditAdminGroups
                AuditReader = $resolvedAuditReaderGroups
                MigrationPlanner = $resolvedMigrationPlannerGroups
            }
        }
        Collector = @{
            PsExecPath = $managedPsExecLivePath
            PsExecSha256 = $managedPsExecHash
            RemoteScriptPath = "\\$env:COMPUTERNAME\$CollectorShareName\collector.ps1"
            RemoteScriptSha256 = $collectorDestinationHash.ToUpperInvariant()
            DeviceTimeoutSeconds = [int](Get-ObjectPathValue $existingProductionSettings @('Collector', 'DeviceTimeoutSeconds') 300)
            MaxDeviceParallelism = [int](Get-ObjectPathValue $existingProductionSettings @('Collector', 'MaxDeviceParallelism') 4)
            JobPollingSeconds = [int](Get-ObjectPathValue $existingProductionSettings @('Collector', 'JobPollingSeconds') 10)
            DailyRunHour = [int](Get-ObjectPathValue $existingProductionSettings @('Collector', 'DailyRunHour') 2)
            DailyRunMinute = [int](Get-ObjectPathValue $existingProductionSettings @('Collector', 'DailyRunMinute') 15)
            RetryMinutes = @(Get-ObjectPathValue $existingProductionSettings @('Collector', 'RetryMinutes') @(30, 120, 1440))
            ExcludeComputersInactiveDays = [int](Get-ObjectPathValue $existingProductionSettings @('Collector', 'ExcludeComputersInactiveDays') 120)
            FallbackTargets = $resolvedFallbackTargets
            DefaultOuFilter = $DefaultOuFilter.Trim()
            DefaultSiteFilter = $DefaultSiteFilter.Trim()
            ExcludeDeviceNames = $resolvedExcludeDeviceNames
            ExcludeOus = $resolvedExcludeOus
            ExcludeUnknownOperatingSystem = [bool]$ExcludeUnknownOperatingSystem
        }
        Copy = @{
            Enabled = $effectiveArtifactCopyEnabled
            DefaultTargetRoot = $resolvedCopyTargetRoot
            AllowedTargetRoots = $resolvedAllowedCopyTargetRoots
            AllowedSourceUncRoots = $resolvedAllowedCopySourceUncRoots
            MaxParallelism = [int](Get-ObjectPathValue $existingProductionSettings @('Copy', 'MaxParallelism') 2)
            BufferSizeMb = [int](Get-ObjectPathValue $existingProductionSettings @('Copy', 'BufferSizeMb') 4)
            VerifySha256 = $effectiveCopyVerifySha256
            MaxAttempts = [int](Get-ObjectPathValue $existingProductionSettings @('Copy', 'MaxAttempts') 2)
            PollingSeconds = [int](Get-ObjectPathValue $existingProductionSettings @('Copy', 'PollingSeconds') 5)
        }
        Retention = @{
            InventoryDays = [int](Get-ObjectPathValue $existingProductionSettings @('Retention', 'InventoryDays') 180)
            CopyJobDays = [int](Get-ObjectPathValue $existingProductionSettings @('Retention', 'CopyJobDays') 365)
            InitialDelayMinutes = [int](Get-ObjectPathValue $existingProductionSettings @('Retention', 'InitialDelayMinutes') 5)
        }
        Diagnostics = @{
            LogDirectory = $logDir
        }
    }

    $settingsPath = Join-Path $appDir 'appsettings.Production.json'
    $productionSettings | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $settingsPath -Encoding utf8

    Assert-NoReparsePointInPath -Path $InstallRoot
    Set-ManagedDirectoryAcl -Path $InstallRoot -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'ReadAndExecute'
    Set-ManagedDirectoryAcl -Path $appDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'ReadAndExecute'
    Set-ManagedDirectoryAcl -Path $appDataDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'Modify'
    Set-ManagedDirectoryAcl -Path $dataDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'Modify'
    Set-ManagedDirectoryAcl -Path $logDir -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'Modify'
    Set-ManagedDirectoryAcl -Path $CollectorSharePath -AdministratorsSid $administratorsSid -SystemSid $systemSid -ServiceSid $serviceIdentity.AclSid -ServiceRights 'ReadAndExecute' -AdditionalReadSid $domainComputers.Sid

    if ($existingService -and $existingService.Status -ne 'Stopped') {
        Stop-Service -Name $ServiceName -Force
        (Get-Service -Name $ServiceName).WaitForStatus('Stopped', [TimeSpan]::FromSeconds(30))
    }

    if (Test-Path -LiteralPath $liveAppDir -PathType Container) {
        Move-Item -LiteralPath $liveAppDir -Destination $rollbackAppDir
    }
    Move-Item -LiteralPath $stagingAppDir -Destination $liveAppDir
    $deploymentSwapped = $true
    $appDir = $liveAppDir
    $applicationExe = Join-Path $appDir 'O365AuditTool.exe'
    $applicationDll = Join-Path $appDir 'O365AuditTool.dll'

    $firewallRuleName = "O365AuditTool-$Port"
    Get-NetFirewallRule -DisplayName 'O365AuditTool-*' -ErrorAction SilentlyContinue |
        Where-Object DisplayName -ne $firewallRuleName |
        Disable-NetFirewallRule | Out-Null
    $firewallRule = Get-NetFirewallRule -DisplayName $firewallRuleName -ErrorAction SilentlyContinue
    if ($firewallRule) {
        $firewallRule | Set-NetFirewallRule -Enabled True -Action Allow -Profile Domain | Out-Null
        $firewallRule | Get-NetFirewallPortFilter | Set-NetFirewallPortFilter -Protocol TCP -LocalPort $Port | Out-Null
    }
    else {
        New-NetFirewallRule -DisplayName $firewallRuleName -Direction Inbound -Action Allow -Profile Domain -Protocol TCP -LocalPort $Port | Out-Null
    }

    $binaryPath = if (Test-Path -LiteralPath $applicationExe -PathType Leaf) {
        "`"$applicationExe`" --environment Production"
    }
    else {
        if ([string]::IsNullOrWhiteSpace($dotnet)) {
            $dotnet = Resolve-DotNetPath -Publishing $false
            Assert-DotNet10 -DotNetPath $dotnet -Publishing $false
        }
        "`"$dotnet`" `"$applicationDll`" --environment Production"
    }
    Configure-Service -Name $ServiceName -BinPath $binaryPath -Identity $serviceIdentity

    Start-Service -Name $ServiceName
    (Get-Service -Name $ServiceName).WaitForStatus('Running', [TimeSpan]::FromSeconds(30))

    $healthUri = "http://127.0.0.1:$HealthPort/health"
    $healthVerified = $false
    for ($attempt = 1; $attempt -le 10; $attempt++) {
        try {
            $healthResponse = Invoke-WebRequest -Uri $healthUri -UseBasicParsing -TimeoutSec 5
            if ($healthResponse.StatusCode -eq 200) {
                $healthVerified = $true
                break
            }
        }
        catch {
            Write-Verbose "Health check denemesi $attempt basarisiz: $($_.Exception.Message)"
        }

        Start-Sleep -Seconds 2
    }

    if (-not $healthVerified) {
        throw "Servis basladi ancak health endpoint dogrulanamadi: '$healthUri'. Event Viewer ve servis loglarini kontrol edin."
    }

    Remove-DeploymentDirectory -Path $rollbackAppDir -Root $InstallRoot
}
catch {
    try {
        $failedService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
        if ($failedService -and $failedService.Status -ne 'Stopped') {
            Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
            $failedService.WaitForStatus('Stopped', [TimeSpan]::FromSeconds(15))
        }

        if ($deploymentSwapped -and (Test-Path -LiteralPath $liveAppDir -PathType Container)) {
            Move-Item -LiteralPath $liveAppDir -Destination $failedAppDir
        }
        if (Test-Path -LiteralPath $rollbackAppDir -PathType Container) {
            Move-Item -LiteralPath $rollbackAppDir -Destination $liveAppDir
        }

        if ($restartOnFailure -and (Test-Path -LiteralPath $liveAppDir -PathType Container)) {
            Start-Service -Name $ServiceName -ErrorAction SilentlyContinue
        }
    }
    catch {
        Write-Warning "Rollback tamamlanamadi. '$rollbackAppDir' ve '$failedAppDir' dizinlerini, Event Viewer'i ve servis kimligini kontrol edin."
    }

    try {
        Write-DeploymentFailureDiagnostics -FailedAppDir $failedAppDir -StagingAppDir $stagingAppDir
    }
    catch {
        Write-Warning "Hata teshis bilgisi yazdirilamadi: $($_.Exception.Message)"
    }
    throw
}

Write-Host "Deployment tamamlandi." -ForegroundColor Green
$dashboardScheme = if ($AllowInsecureHttpDashboard) { 'http' } else { 'https' }
Write-Host "Dashboard: $dashboardScheme`://$resolvedDashboardDnsName`:$Port" -ForegroundColor Cyan
Write-Host "Collector share: \\$env:COMPUTERNAME\$CollectorShareName\collector.ps1" -ForegroundColor Cyan
Write-Host "Service: $ServiceName ($($serviceIdentity.Type): $($serviceIdentity.ScAccount))" -ForegroundColor Cyan
Write-Host "Tarama kapsami: OU='$($DefaultOuFilter.Trim())' Site='$($DefaultSiteFilter.Trim())'" -ForegroundColor Cyan
if ($resolvedExcludeDeviceNames.Count -gt 0 -or $resolvedExcludeOus.Count -gt 0) {
    Write-Host "Haric tutulan cihazlar: $($resolvedExcludeDeviceNames -join ', ')" -ForegroundColor Cyan
    Write-Host "Haric tutulan OU'lar: $($resolvedExcludeOus -join ', ')" -ForegroundColor Cyan
}
if ($effectiveArtifactCopyEnabled) {
    Write-Host "Artifact copy: ENABLED -> $resolvedCopyTargetRoot (SHA256: $effectiveCopyVerifySha256)" -ForegroundColor Yellow
}
else {
    Write-Host "Artifact copy: disabled (opt-in icin -EnableArtifactCopy gerekir)" -ForegroundColor DarkYellow
}
